### ISSUE TITLE
ionic cordova resources command fails

### ISSUE THREAD

**Issue by muratcorlu** [ionic-zone/fastlane-plugin-ionic#45]
I use ionic command to build my app with this parameters:

```
ionic(
      platform: 'ios',
      build_number: latest_build + 1,
      prod: true,
      release: true,
      device: true,
      cordova_prepare: true,
      build_flag: [
        "EMBEDDED_CONTENT_CONTAINS_SWIFT = YES",
        "ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES=NO",
        "LD_RUNPATH_SEARCH_PATHS = \"@executable_path/Frameworks\"",
        "-UseModernBuildSystem=0"
      ]
    )
```

But somehow this is calling `ionic cordova resources` command and it fails.

```
> ionic cordova resources ios --force
[ERROR] Source image files were not found for the following platforms/types:

        - ios/icon
        - ios/splash
```

Is this part of this plugin? Can I skip this step? Because I manage creating resources manually.

**Comment by janpio** [comment]
The plugin "just" calls out to the `ionic` CLI from Ionic, and seems they added that step in there somewhere.

If you post your complete output, I might be able to see which of their commands is doing this and find out if they have a param that disables this behavior - and add it to the plugin.

**Comment by muratcorlu** [comment]
I added full output:

<details><pre>
$ fastlane ios beta
[18:19:32]: fastlane detected a Gemfile in the current directory
[18:19:32]: however it seems like you don't use `bundle exec`
[18:19:32]: to launch fastlane faster, please use
[18:19:32]: 
[18:19:32]: $ bundle exec fastlane ios beta
[18:19:32]: 
[18:19:32]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
+-------------------------------------+---------+--------------------------------------+
|                                     Used plugins                                     |
+-------------------------------------+---------+--------------------------------------+
| Plugin                              | Version | Action                               |
+-------------------------------------+---------+--------------------------------------+
| fastlane-plugin-cordova_screenshots | 0.2.0   | init_cordova_screenshots_ios         |
|                                     |         | retrofit_cordova_screenshots_android |
|                                     |         | retrofit_cordova_screenshots_ios     |
|                                     |         | init_cordova_screenshots_android     |
| fastlane-plugin-ionic               | 0.1.0   | ionic                                |
+-------------------------------------+---------+--------------------------------------+

[18:19:34]: ----------------------------------------
[18:19:34]: --- Step: Verifying fastlane version ---
[18:19:34]: ----------------------------------------
[18:19:34]: Your fastlane version 2.120.0 matches the minimum requirement of 2.78.0  ✅
[18:19:34]: ------------------------------
[18:19:34]: --- Step: default_platform ---
[18:19:34]: ------------------------------
[18:19:34]: Driving the lane 'ios beta' 🚀
[18:19:34]: -------------------
[18:19:34]: --- Step: match ---
[18:19:34]: -------------------
[18:19:35]: Successfully loaded '/Users/muratcorlu/builds/_LBovLxB/0/bilibu/bilibu-mobile/fastlane/Matchfile' 📄

+--------------+----------------------------------------+
|      Detected Values from './fastlane/Matchfile'      |
+--------------+----------------------------------------+
| git_url      | git@gitlab.com:****/certificates.git |
| storage_mode | git                                    |
| type         | appstore                               |
+--------------+----------------------------------------+


+-----------------------+----------------------------------------+
|                   Summary for match 2.120.0                    |
+-----------------------+----------------------------------------+
| type                  | appstore                               |
| readonly              | true                                   |
| app_identifier        | ["com.bilibu.*******"]                |
| username              | muratcorlu@**.com                      |
| team_id               | UDCL858977                             |
| storage_mode          | git                                    |
| git_url               | git@gitlab.com:****/certificates.git |
| git_branch            | master                                 |
| shallow_clone         | false                                  |
| clone_branch_directly | false                                  |
| keychain_name         | login.keychain                         |
| force                 | false                                  |
| force_for_new_devices | false                                  |
| skip_confirmation     | false                                  |
| skip_docs             | false                                  |
| platform              | ios                                    |
| verbose               | false                                  |
+-----------------------+----------------------------------------+

[18:19:35]: Cloning remote git repo...
[18:19:35]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[18:19:38]: 🔓  Successfully decrypted certificates repo
[18:19:38]: Installing certificate...

+-------------------+-----------------------------------------------+
|                       Installed Certificate                       |
+-------------------+-----------------------------------------------+
| User ID           | *******                                    |
| Common Name       | iPhone Distribution: Murat Corlu (******) |
| Organisation Unit | ******                                    |
| Organisation      | Murat Corlu                                   |
| Country           | US                                            |
| Start Datetime    | 2019-04-19 17:30:14 UTC                       |
| End Datetime      | 2020-04-18 17:30:14 UTC                       |
+-------------------+-----------------------------------------------+

[18:19:38]: Installing provisioning profile...

+---------------------+------------------------------------------------+-------------------------------------------------------------------------------------------------------------------+
|                                                                              Installed Provisioning Profile                                                                              |
+---------------------+------------------------------------------------+-------------------------------------------------------------------------------------------------------------------+
| Parameter           | Environment Variable                           | Value                                                                                                             |
+---------------------+------------------------------------------------+-------------------------------------------------------------------------------------------------------------------+
| App Identifier      |                                                | com.bilibu.****                                                                                               |
| Type                |                                                | appstore                                                                                                          |
| Platform            |                                                | ios                                                                                                               |
| Profile UUID        | sigh_com.bilibu.****_appstore              | *******                                                                              |
| Profile Name        | sigh_com.bilibu.****_appstore_profile-name | match AppStore com.bilibu.**** ***                                                                     |
| Profile Path        | sigh_com.bilibu.****_appstore_profile-path | /Users/muratcorlu/Library/MobileDevice/Provisioning Profiles/*******.mobileprovision |
| Development Team ID | sigh_com.bilibu.****_appstore_team-id      | *******                                                                                                        |
+---------------------+------------------------------------------------+-------------------------------------------------------------------------------------------------------------------+

[18:19:38]: All required keys, certificates and provisioning profiles are installed 🙌
[18:19:38]: Setting Provisioning Profile type to 'app-store'
[18:19:38]: ------------------------------------
[18:19:38]: --- Step: app_store_build_number ---
[18:19:38]: ------------------------------------
[18:19:38]: Login to App Store Connect (muratcorlu@****.com)
[18:19:40]: Login successful
[18:19:42]: Fetching the latest build number for version 2.0.0
[18:19:42]: Latest upload for version 2.0.0 is build: 14
[18:19:42]: Latest build number:
[18:19:42]: 14
[18:19:42]: -------------------
[18:19:42]: --- Step: ionic ---
[18:19:42]: -------------------
[18:19:42]: $ ionic cordova platform add ios --no-interactive
[18:19:43]: ▸ ✔ Creating ./www directory for you - done!
[18:19:43]: ▸ &gt; cordova platform add ios --save
[18:19:45]: ▸ Using cordova-fetch for cordova-ios@^4.5.5
[18:20:16]: ▸ Adding ios project...
[18:20:17]: ▸ Creating Cordova project for the iOS platform:
[18:20:17]: ▸ Path: platforms/ios
[18:20:17]: ▸ Package: com.bilibu.****
[18:20:17]: ▸ Name: Football Expert
[18:20:17]: ▸ iOS project created with cordova-ios@4.5.5
[18:20:18]: ▸ Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the project
[18:20:47]: ▸ Installing "cordova-plugin-whitelist" for ios
[18:20:47]: ▸ Adding cordova-plugin-whitelist to package.json
[18:20:47]: ▸ Saved plugin info for "cordova-plugin-whitelist" to config.xml
[18:20:47]: ▸ Discovered plugin "cordova-plugin-statusbar" in config.xml. Adding it to the project
[18:21:11]: ▸ Installing "cordova-plugin-statusbar" for ios
[18:21:12]: ▸ Adding cordova-plugin-statusbar to package.json
[18:21:12]: ▸ Saved plugin info for "cordova-plugin-statusbar" to config.xml
[18:21:12]: ▸ Discovered plugin "cordova-plugin-splashscreen" in config.xml. Adding it to the project
[18:21:39]: ▸ Installing "cordova-plugin-splashscreen" for ios
[18:21:39]: ▸ Adding cordova-plugin-splashscreen to package.json
[18:21:39]: ▸ Saved plugin info for "cordova-plugin-splashscreen" to config.xml
[18:21:39]: ▸ Discovered plugin "cordova-plugin-ionic-webview" in config.xml. Adding it to the project
[18:22:16]: ▸ Installing "cordova-plugin-ionic-webview" for ios
[18:22:17]: ▸ Adding cordova-plugin-ionic-webview to package.json
[18:22:17]: ▸ Saved plugin info for "cordova-plugin-ionic-webview" to config.xml
[18:22:18]: ▸ Discovered plugin "cordova-plugin-ionic-keyboard" in config.xml. Adding it to the project
[18:23:00]: ▸ Installing "cordova-plugin-ionic-keyboard" for ios
[18:23:00]: ▸ Adding cordova-plugin-ionic-keyboard to package.json
[18:23:00]: ▸ Saved plugin info for "cordova-plugin-ionic-keyboard" to config.xml
[18:23:00]: ▸ Discovered plugin "cordova-plugin-device" in config.xml. Adding it to the project
[18:23:24]: ▸ Installing "cordova-plugin-device" for ios
[18:23:24]: ▸ Adding cordova-plugin-device to package.json
[18:23:24]: ▸ Saved plugin info for "cordova-plugin-device" to config.xml
[18:23:24]: ▸ Discovered plugin "cordova-sqlite-storage" in config.xml. Adding it to the project
[18:23:47]: ▸ Installing "cordova-sqlite-storage" for ios
[18:23:47]: ▸ installing external dependencies via npm
[18:23:49]: ▸ npm install of external dependencies ok
[18:23:49]: ▸ Adding cordova-sqlite-storage to package.json
[18:23:49]: ▸ Saved plugin info for "cordova-sqlite-storage" to config.xml
[18:23:49]: ▸ Discovered plugin "ionic-plugin-deeplinks" in config.xml. Adding it to the project
[18:24:14]: ▸ Installing "ionic-plugin-deeplinks" for ios
[18:24:14]: ▸ Adding ionic-plugin-deeplinks to package.json
[18:24:14]: ▸ Saved plugin info for "ionic-plugin-deeplinks" to config.xml
[18:24:14]: ▸ Discovered plugin "cordova-plugin-x-socialsharing" in config.xml. Adding it to the project
[18:24:37]: ▸ Installing "cordova-plugin-x-socialsharing" for ios
[18:24:59]: ▸ Installing "es6-promise-plugin" for ios
[18:24:59]: ▸ Adding cordova-plugin-x-socialsharing to package.json
[18:24:59]: ▸ Saved plugin info for "cordova-plugin-x-socialsharing" to config.xml
[18:24:59]: ▸ Discovered plugin "cordova-plugin-media" in config.xml. Adding it to the project
[18:25:21]: ▸ Installing "cordova-plugin-media" for ios
[18:25:44]: ▸ Installing "cordova-plugin-file" for ios
[18:25:44]: ▸ Adding cordova-plugin-media to package.json
[18:25:44]: ▸ Saved plugin info for "cordova-plugin-media" to config.xml
[18:25:44]: ▸ Discovered plugin "app-entitlements" in config.xml. Adding it to the project
[18:26:05]: ▸ Installing "app-entitlements" for ios
[18:26:05]: ▸ Adding app-entitlements to package.json
[18:26:05]: ▸ Saved plugin info for "app-entitlements" to config.xml
[18:26:05]: ▸ Discovered plugin "cordova-plugin-globalization" in config.xml. Adding it to the project
[18:26:26]: ▸ Installing "cordova-plugin-globalization" for ios
[18:26:26]: ▸ Adding cordova-plugin-globalization to package.json
[18:26:26]: ▸ Saved plugin info for "cordova-plugin-globalization" to config.xml
[18:26:26]: ▸ Discovered plugin "cordova-plugin-admob-free" in config.xml. Adding it to the project
[18:26:46]: ▸ Installing "cordova-plugin-admob-free" for ios
[18:27:06]: ▸ Installing "cordova-promise-polyfill" for ios
[18:27:27]: ▸ Installing "cordova-admob-sdk" for ios
[18:27:27]: ▸ Adding cordova-plugin-admob-free to package.json
[18:27:27]: ▸ Saved plugin info for "cordova-plugin-admob-free" to config.xml
[18:27:27]: ▸ Discovered plugin "cordova-plugin-inapppurchase" in config.xml. Adding it to the project
[18:27:46]: ▸ Installing "cordova-plugin-inapppurchase" for ios
[18:27:46]: ▸ Adding cordova-plugin-inapppurchase to package.json
[18:27:46]: ▸ Saved plugin info for "cordova-plugin-inapppurchase" to config.xml
[18:27:46]: ▸ Discovered plugin "cordova-plugin-advanced-http" in config.xml. Adding it to the project
[18:28:04]: ▸ Installing "cordova-plugin-advanced-http" for ios
[18:28:04]: ▸ Plugin dependency "cordova-plugin-file@6.0.1" already fetched, using that version.
[18:28:04]: ▸ Dependent plugin "cordova-plugin-file" already installed on ios.
[18:28:04]: ▸ Adding cordova-plugin-advanced-http to package.json
[18:28:04]: ▸ Saved plugin info for "cordova-plugin-advanced-http" to config.xml
[18:28:04]: ▸ Discovered plugin "cordova-plugin-screen-orientation" in config.xml. Adding it to the project
[18:28:23]: ▸ Installing "cordova-plugin-screen-orientation" for ios
[18:28:23]: ▸ Adding cordova-plugin-screen-orientation to package.json
[18:28:23]: ▸ Saved plugin info for "cordova-plugin-screen-orientation" to config.xml
[18:28:23]: ▸ --save flag or autosave detected
[18:28:23]: ▸ Saving ios@~4.5.5 into config.xml file ...
[18:28:23]: ▸ > ionic cordova resources ios --force
[18:28:23]: ▸ [ERROR] Source image files were not found for the following platforms/types:
[18:28:23]: ▸ - ios/icon
[18:28:23]: ▸ - ios/splash
[18:28:23]: ▸ Please review --help
+------------------------------------+--------------------------------------------------------------------------+
|                                                 Lane Context                                                  |
+------------------------------------+--------------------------------------------------------------------------+
| DEFAULT_PLATFORM                   | ios                                                                      |
| PLATFORM_NAME                      | ios                                                                      |
| LANE_NAME                          | ios beta                                                                 |
| SIGH_PROFILE_TYPE                  | app-store                                                                |
| MATCH_PROVISIONING_PROFILE_MAPPING | {"com.bilibu.*****"=>"match AppStore com.bilibu.**** ****"} |
| LATEST_BUILD_NUMBER                | 14                                                                       |
+------------------------------------+--------------------------------------------------------------------------+
[18:28:23]: Exit status of command 'ionic cordova platform add ios --no-interactive' was 1 instead of 0.
✔ Creating ./www directory for you - done!
&gt; cordova platform add ios --save
Using cordova-fetch for cordova-ios@^4.5.5
Adding ios project...
Creating Cordova project for the iOS platform:
	Path: platforms/ios
	Package: com.bilibu.****
	Name: Football Expert
iOS project created with cordova-ios@4.5.5
Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the project
Installing "cordova-plugin-whitelist" for ios
Adding cordova-plugin-whitelist to package.json
Saved plugin info for "cordova-plugin-whitelist" to config.xml
Discovered plugin "cordova-plugin-statusbar" in config.xml. Adding it to the project
Installing "cordova-plugin-statusbar" for ios
Adding cordova-plugin-statusbar to package.json
Saved plugin info for "cordova-plugin-statusbar" to config.xml
Discovered plugin "cordova-plugin-splashscreen" in config.xml. Adding it to the project
Installing "cordova-plugin-splashscreen" for ios
Adding cordova-plugin-splashscreen to package.json
Saved plugin info for "cordova-plugin-splashscreen" to config.xml
Discovered plugin "cordova-plugin-ionic-webview" in config.xml. Adding it to the project
Installing "cordova-plugin-ionic-webview" for ios
Adding cordova-plugin-ionic-webview to package.json
Saved plugin info for "cordova-plugin-ionic-webview" to config.xml
Discovered plugin "cordova-plugin-ionic-keyboard" in config.xml. Adding it to the project
Installing "cordova-plugin-ionic-keyboard" for ios
Adding cordova-plugin-ionic-keyboard to package.json
Saved plugin info for "cordova-plugin-ionic-keyboard" to config.xml
Discovered plugin "cordova-plugin-device" in config.xml. Adding it to the project
Installing "cordova-plugin-device" for ios
Adding cordova-plugin-device to package.json
Saved plugin info for "cordova-plugin-device" to config.xml
Discovered plugin "cordova-sqlite-storage" in config.xml. Adding it to the project
Installing "cordova-sqlite-storage" for ios
installing external dependencies via npm
npm install of external dependencies ok
Adding cordova-sqlite-storage to package.json
Saved plugin info for "cordova-sqlite-storage" to config.xml
Discovered plugin "ionic-plugin-deeplinks" in config.xml. Adding it to the project
Installing "ionic-plugin-deeplinks" for ios
Adding ionic-plugin-deeplinks to package.json
Saved plugin info for "ionic-plugin-deeplinks" to config.xml
Discovered plugin "cordova-plugin-x-socialsharing" in config.xml. Adding it to the project
Installing "cordova-plugin-x-socialsharing" for ios
Installing "es6-promise-plugin" for ios
Adding cordova-plugin-x-socialsharing to package.json
Saved plugin info for "cordova-plugin-x-socialsharing" to config.xml
Discovered plugin "cordova-plugin-media" in config.xml. Adding it to the project
Installing "cordova-plugin-media" for ios
Installing "cordova-plugin-file" for ios
Adding cordova-plugin-media to package.json
Saved plugin info for "cordova-plugin-media" to config.xml
Discovered plugin "app-entitlements" in config.xml. Adding it to the project
Installing "app-entitlements" for ios
Adding app-entitlements to package.json
Saved plugin info for "app-entitlements" to config.xml
Discovered plugin "cordova-plugin-globalization" in config.xml. Adding it to the project
Installing "cordova-plugin-globalization" for ios
Adding cordova-plugin-globalization to package.json
Saved plugin info for "cordova-plugin-globalization" to config.xml
Discovered plugin "cordova-plugin-admob-free" in config.xml. Adding it to the project
Installing "cordova-plugin-admob-free" for ios
Installing "cordova-promise-polyfill" for ios
Installing "cordova-admob-sdk" for ios
Adding cordova-plugin-admob-free to package.json
Saved plugin info for "cordova-plugin-admob-free" to config.xml
Discovered plugin "cordova-plugin-inapppurchase" in config.xml. Adding it to the project
Installing "cordova-plugin-inapppurchase" for ios
Adding cordova-plugin-inapppurchase to package.json
Saved plugin info for "cordova-plugin-inapppurchase" to config.xml
Discovered plugin "cordova-plugin-advanced-http" in config.xml. Adding it to the project
Installing "cordova-plugin-advanced-http" for ios
Plugin dependency "cordova-plugin-file@6.0.1" already fetched, using that version.
Dependent plugin "cordova-plugin-file" already installed on ios.
Adding cordova-plugin-advanced-http to package.json
Saved plugin info for "cordova-plugin-advanced-http" to config.xml
Discovered plugin "cordova-plugin-screen-orientation" in config.xml. Adding it to the project
Installing "cordova-plugin-screen-orientation" for ios
Adding cordova-plugin-screen-orientation to package.json
Saved plugin info for "cordova-plugin-screen-orientation" to config.xml
--save flag or autosave detected
Saving ios@~4.5.5 into config.xml file ...
&gt; ionic cordova resources ios --force
[ERROR] Source image files were not found for the following platforms/types:
        
        - ios/icon
        - ios/splash
        
        Please review --help


+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 2    | default_platform           | 0           |
| 3    | match                      | 3           |
| 4    | app_store_build_number     | 4           |
| 💥   | ionic                      | 521         |
+------+----------------------------+-------------+

[18:28:23]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

WARNING: You are running Ruby 2.2.4, which has reached end-of-life and is no longer supported by Ruby Core.
The Google Cloud API clients work best on supported versions of Ruby. It is strongly recommended that you upgrade to Ruby 2.4 or later.
See https://www.ruby-lang.org/en/downloads/branches/ for more info on the Ruby maintenance schedule.
To suppress this message, set the GOOGLE_CLOUD_SUPPRESS_RUBY_WARNINGS environment variable.
/Users/muratcorlu/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.120.0/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': [!] Exit status of command 'ionic cordova platform add ios --no-interactive' was 1 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
✔ Creating ./www directory for you - done!
&gt; cordova platform add ios --save
Using cordova-fetch for cordova-ios@^4.5.5
Adding ios project...
Creating Cordova project for the iOS platform:
	Path: platforms/ios
	Package: com.bilibu.*****
	Name: Football Expert
iOS project created with cordova-ios@4.5.5
Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the project
Installing "cordova-plugin-whitelist" for ios
Adding cordova-plugin-whitelist to package.json
Saved plugin info for "cordova-plugin-whitelist" to config.xml
Discovered plugin "cordova-plugin-statusbar" in config.xml. Adding it to the project
Installing "cordova-plugin-statusbar" for ios
Adding cordova-plugin-statusbar to package.json
Saved plugin info for "cordova-plugin-statusbar" to config.xml
Discovered plugin "cordova-plugin-splashscreen" in config.xml. Adding it to the project
Installing "cordova-plugin-splashscreen" for ios
Adding cordova-plugin-splashscreen to package.json
Saved plugin info for "cordova-plugin-splashscreen" to config.xml
Discovered plugin "cordova-plugin-ionic-webview" in config.xml. Adding it to the project
Installing "cordova-plugin-ionic-webview" for ios
Adding cordova-plugin-ionic-webview to package.json
Saved plugin info for "cordova-plugin-ionic-webview" to config.xml
Discovered plugin "cordova-plugin-ionic-keyboard" in config.xml. Adding it to the project
Installing "cordova-plugin-ionic-keyboard" for ios
Adding cordova-plugin-ionic-keyboard to package.json
Saved plugin info for "cordova-plugin-ionic-keyboard" to config.xml
Discovered plugin "cordova-plugin-device" in config.xml. Adding it to the project
Installing "cordova-plugin-device" for ios
Adding cordova-plugin-device to package.json
Saved plugin info for "cordova-plugin-device" to config.xml
Discovered plugin "cordova-sqlite-storage" in config.xml. Adding it to the project
Installing "cordova-sqlite-storage" for ios
installing external dependencies via npm
npm install of external dependencies ok
Adding cordova-sqlite-storage to package.json
Saved plugin info for "cordova-sqlite-storage" to config.xml
Discovered plugin "ionic-plugin-deeplinks" in config.xml. Adding it to the project
Installing "ionic-plugin-deeplinks" for ios
Adding ionic-plugin-deeplinks to package.json
Saved plugin info for "ionic-plugin-deeplinks" to config.xml
Discovered plugin "cordova-plugin-x-socialsharing" in config.xml. Adding it to the project
Installing "cordova-plugin-x-socialsharing" for ios
Installing "es6-promise-plugin" for ios
Adding cordova-plugin-x-socialsharing to package.json
Saved plugin info for "cordova-plugin-x-socialsharing" to config.xml
Discovered plugin "cordova-plugin-media" in config.xml. Adding it to the project
Installing "cordova-plugin-media" for ios
Installing "cordova-plugin-file" for ios
Adding cordova-plugin-media to package.json
Saved plugin info for "cordova-plugin-media" to config.xml
Discovered plugin "app-entitlements" in config.xml. Adding it to the project
Installing "app-entitlements" for ios
Adding app-entitlements to package.json
Saved plugin info for "app-entitlements" to config.xml
Discovered plugin "cordova-plugin-globalization" in config.xml. Adding it to the project
Installing "cordova-plugin-globalization" for ios
Adding cordova-plugin-globalization to package.json
Saved plugin info for "cordova-plugin-globalization" to config.xml
Discovered plugin "cordova-plugin-admob-free" in config.xml. Adding it to the project
Installing "cordova-plugin-admob-free" for ios
Installing "cordova-promise-polyfill" for ios
Installing "cordova-admob-sdk" for ios
Adding cordova-plugin-admob-free to package.json
Saved plugin info for "cordova-plugin-admob-free" to config.xml
Discovered plugin "cordova-plugin-inapppurchase" in config.xml. Adding it to the project
Installing "cordova-plugin-inapppurchase" for ios
Adding cordova-plugin-inapppurchase to package.json
Saved plugin info for "cordova-plugin-inapppurchase" to config.xml
Discovered plugin "cordova-plugin-advanced-http" in config.xml. Adding it to the project
Installing "cordova-plugin-advanced-http" for ios
Plugin dependency "cordova-plugin-file@6.0.1" already fetched, using that version.
Dependent plugin "cordova-plugin-file" already installed on ios.
Adding cordova-plugin-advanced-http to package.json
Saved plugin info for "cordova-plugin-advanced-http" to config.xml
Discovered plugin "cordova-plugin-screen-orientation" in config.xml. Adding it to the project
Installing "cordova-plugin-screen-orientation" for ios
Adding cordova-plugin-screen-orientation to package.json
Saved plugin info for "cordova-plugin-screen-orientation" to config.xml
--save flag or autosave detected
Saving ios@~4.5.5 into config.xml file ...
&gt; ionic cordova resources ios --force
[ERROR] Source image files were not found for the following platforms/types:
        
        - ios/icon
        - ios/splash
        
        Please review --help

	from /Users/muratcorlu/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.120.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Users/muratcorlu/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.120.0/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
	from /Users/muratcorlu/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-plugin-ionic-0.1.0/lib/fastlane/plugin/ionic/actions/ionic_action.rb:85:in `check_platform'
	from /Users/muratcorlu/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-plugin-ionic-0.1.0/lib/fastlane/plugin/ionic/actions/ionic_action.rb:146:in `run'
	from /Users/muratcorlu/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.120.0/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
	from /Users/muratcorlu/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.120.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/muratcorlu/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.120.0/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
	from /Users/muratcorlu/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.120.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Users/muratcorlu/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.120.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Users/muratcorlu/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.120.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/muratcorlu/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.120.0/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
	from Fastfile:82:in `block (2 levels) in parsing_binding'
	from /Users/muratcorlu/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.120.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/muratcorlu/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.120.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/muratcorlu/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.120.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/muratcorlu/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.120.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/muratcorlu/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.120.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/muratcorlu/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.120.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Users/muratcorlu/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.120.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/muratcorlu/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.120.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/muratcorlu/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/muratcorlu/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/muratcorlu/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/muratcorlu/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/muratcorlu/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.120.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Users/muratcorlu/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/muratcorlu/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.120.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	from /Users/muratcorlu/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.120.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Users/muratcorlu/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.120.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	from /Users/muratcorlu/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.120.0/bin/fastlane:23:in `<top (required)>'
	from /Users/muratcorlu/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/muratcorlu/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
ERROR: Job failed: exit status 1

</pre></details>

**Comment by janpio** [comment]
Ok, that seems to happen during the `ionic cordova platform add` step already.

```
λ ionic help cordova platform

  ionic cordova platform - Manage Cordova platform targets

    Like running cordova platform directly, but adds default Ionic icons and splash screen resources (during add) and
    provides friendly checks.

  Usage:

    $ ionic cordova platform [<action>] [<platform>] [options]

  Inputs:

    action .......................... add, remove, or update a platform; ls, check, or save all project platforms
    platform ........................ The platform that you would like to add (android, ios)

  Options:

    --no-resources .................. Do not pregenerate icons and splash screen resources (corresponds to add)

  Examples:

    $ ionic cordova platform
    $ ionic cordova platform add ios
    $ ionic cordova platform add android
    $ ionic cordova platform rm ios
```

So `--no-resources` would probably be a fix for you.

**Comment by janpio** [comment]
You might try to run `ionic cordova platform add ios --no-resources` yourself manually before calling `ionic`, this might make the plugin to skip that step and let you proceed.
